### ISSUE TITLE
Missing RPGG.tar.gz file

### ISSUE THREAD

**Issue by 491326431** [ChaissonLab/danbing-tk#14]
Hi, I tried to run this soft. When I followed the guidance, I can 't find RPGG.tar.gz file in the package downloaded. Did I missed anything or this file is no longer needed? Thanks for ur help.

Best.
Abel

**Comment by joyeuxnoel8** [comment]
Hi Abel,

The latest RPGG can be found here under [release v1.3](https://github.com/ChaissonLab/danbing-tk/releases/tag/v1.3).

-Tony
