### ISSUE TITLE
Assertion `its.size()' failed error in danbing-tk align

### ISSUE THREAD

**Issue by Skye722** [ChaissonLab/danbing-tk#21]
Hi,

When testing a sample from the 1000 Genomes Project using **danbing-tk align** module, I encountered the error message:

> danbing-tk: src/aQueryFasta_thread.cpp:128: void countDupRemove(std::vector<std::__detail::_Node_iterator<std::pair<const long unsigned int, long unsigned int>, false, false> >&, std::vector<std::__detail::_Node_iterator<std::pair<const long unsigned int, long unsigned int>, false, false> >&, std::vector<std::pair<unsigned char, unsigned char> >&): Assertion `its.size()' failed.

The commend I used is as follow:
`samtools fasta  -n HG00096.bam |./danbing-tk -gc 80 -ae -kf 4 0 -cth 45 -o test -k 21 -qs pan -fai /dev/stdin -p 2 |gzip >test.aln.gz`

The complete log is pleased to be provided if you need.

Thank you for helping me out!

Best,
Skye

**Comment by maryamghr** [comment]
Hi,

I have faced exactly the same error. Could you figure out the reason for this error?

Bests,
Maryam

**Comment by joyeuxnoel8** [comment]
Hi all,

Sorry for the huge delay. Could you try `-kf 4 1` instead? The program currently works only with the kmer filter (kf) turned on (the second integer has to be greater than 0). Let me know if you still run into any issues. Thanks!

-Tony

**Comment by Skye722** [comment]
> 

Yeah, it works with `-kf 4 1`. Thanks a lot!
