### ISSUE TITLE
danbing-tk: src/aQueryFasta_thread.cpp:1194 int main(int, char**): Assertion ´tfFile´ failed

### ISSUE THREAD

**Issue by dbeyter** [ChaissonLab/danbing-tk#22]
Hi, 

I ran the sample command provided for danbing-tk as:
samtools fasta -@2 -n $SRS.bam |
/$PREFIX/danbing-tk/bin/danbing-tk -gc 80 -ae -kf 4 1 -cth 45 -o $OUT_PREF -k 21 -qs pan -fai /dev/stdin -p $THREADS 

and have received:
danbing-tk: src/aQueryFasta_thread.cpp:1194 int main(int, char**): Assertion ´tfFile´ failed
Aborted (core dumped) 

as soon as I run the command above with no other log/progress.

Any help would be appreciated to see why this may be happening.
Thank you, 
Doruk

**Comment by joyeuxnoel8** [comment]
Hi Doruk,

Thanks for reaching out. Did you happen to place graph index files under a different directory? It's possible to read the indices from a different directory with `-qs $PATH_TO_INDEX/pan`, assuming you're using the indices we provided. 

Thanks,
-Tony

**Comment by dbeyter** [comment]
Hi Tony, 

It seems the purpose of the -qs parameter was unclear to me. Thank you for explaining!

Doruk
