### ISSUE TITLE
error encountered in the example snakemake command

### ISSUE THREAD

**Issue by dbeyter** [ChaissonLab/danbing-tk#6]
Dear ChaissonLab, 

I tried running the test example command using snakemake. I encountered the error message:

KeyError in line 10 of GoodPangenomeGraph.snakefile:
'pruning'

There indeed appears no key "pruning" in the goodPanGenomeGraph.json file. 

Thanks!

**Comment by joyeuxnoel8** [comment]
Thanks for reporting! I've updated the test example to include the latest change. Let me know if it works, thanks!

**Comment by dbeyter** [comment]
Thank you for the update! I had other problems in the downstream, but this fixed the specified issue.
